/*
 * Insert guesses for Arnar Jónasson
 */
insert into guess(question_id, person_id) values(1, 1);
insert into base_guess (guess, whitewalker, guess_id) values('f', 'f', 1);
insert into guess(question_id, person_id) values(2, 1);
insert into base_guess (guess, whitewalker, guess_id) values('t', 'f', 2);
insert into guess(question_id, person_id) values(3, 1);
insert into base_guess (guess, whitewalker, guess_id) values('t', 'f', 3);
insert into guess(question_id, person_id) values(4, 1);
insert into base_guess (guess, whitewalker, guess_id) values('t', 'f', 4);
insert into guess(question_id, person_id) values(5, 1);
insert into base_guess (guess, whitewalker, guess_id) values('f', 'f', 5);
insert into guess(question_id, person_id) values(6, 1);
insert into base_guess (guess, whitewalker, guess_id) values('f', 'f', 6);
insert into guess(question_id, person_id) values(7, 1);
insert into base_guess (guess, whitewalker, guess_id) values('t', 'f', 7);
insert into guess(question_id, person_id) values(8, 1);
insert into base_guess (guess, whitewalker, guess_id) values('t', 'f', 8);
insert into guess(question_id, person_id) values(9, 1);
insert into base_guess (guess, whitewalker, guess_id) values('t', 't', 9);
insert into guess(question_id, person_id) values(10, 1);
insert into base_guess (guess, whitewalker, guess_id) values('t', 'f', 10);
insert into guess(question_id, person_id) values(11, 1);
insert into base_guess (guess, whitewalker, guess_id) values('f', 'f', 11);
insert into guess(question_id, person_id) values(12, 1);
insert into base_guess (guess, whitewalker, guess_id) values('f', 'f', 12);
insert into guess(question_id, person_id) values(13, 1);
insert into base_guess (guess, whitewalker, guess_id) values('f', 'f', 13);
insert into guess(question_id, person_id) values(14, 1);
insert into base_guess (guess, whitewalker, guess_id) values('f', 'f', 14);
insert into guess(question_id, person_id) values(15, 1);
insert into base_guess (guess, whitewalker, guess_id) values('t', 'f', 15);
insert into guess(question_id, person_id) values(16, 1);
insert into base_guess (guess, whitewalker, guess_id) values('t', 'f', 16);
insert into guess(question_id, person_id) values(17, 1);
insert into base_guess (guess, whitewalker, guess_id) values('t', 'f', 17);
insert into guess(question_id, person_id) values(18, 1);
insert into base_guess (guess, whitewalker, guess_id) values('f', 'f', 18);
insert into guess(question_id, person_id) values(19, 1);
insert into base_guess (guess, whitewalker, guess_id) values('t', 'f', 19);
insert into guess(question_id, person_id) values(20, 1);
insert into base_guess (guess, whitewalker, guess_id) values('f', 'f', 20);
insert into guess(question_id, person_id) values(21, 1);
insert into base_guess (guess, whitewalker, guess_id) values('t', 'f', 21);
insert into guess(question_id, person_id) values(22, 1);
insert into base_guess (guess, whitewalker, guess_id) values('t', 'f', 22);
insert into guess(question_id, person_id) values(23, 1);
insert into base_guess (guess, whitewalker, guess_id) values('t', 'f', 23);
insert into guess(question_id, person_id) values(24, 1);
insert into base_guess (guess, whitewalker, guess_id) values('f', 'f', 24);
insert into guess(question_id, person_id) values(25, 1);
insert into base_guess (guess, whitewalker, guess_id) values('t', 'f', 25);
insert into guess(question_id, person_id) values(26, 1);
insert into base_guess (guess, whitewalker, guess_id) values('f', 'f', 26);
insert into guess(question_id, person_id) values(27, 1);
insert into base_guess (guess, whitewalker, guess_id) values('f', 'f', 27);
insert into guess(question_id, person_id) values(28, 1);
insert into bonus_guess (guess, guess_id) values('Yes', 28);
insert into guess(question_id, person_id) values(29, 1);
insert into bonus_guess (guess, guess_id) values('No', 29);
insert into guess(question_id, person_id) values(30, 1);
insert into bonus_guess (guess, guess_id) values('Jon Snow', 30);
insert into guess(question_id, person_id) values(31, 1);
insert into bonus_guess (guess, guess_id) values('', 31);
insert into guess(question_id, person_id) values(32, 1);
insert into bonus_guess (guess, guess_id) values('Daenerys Targaryen', 32);


/*
 * Insert guesses for Bergsteinn Árnason
 */
insert into guess(question_id, person_id) values(1, 2);
insert into base_guess (guess, whitewalker, guess_id) values('f', 'f', 33);
insert into guess(question_id, person_id) values(2, 2);
insert into base_guess (guess, whitewalker, guess_id) values('t', 'f', 34);
insert into guess(question_id, person_id) values(3, 2);
insert into base_guess (guess, whitewalker, guess_id) values('t', 'f', 35);
insert into guess(question_id, person_id) values(4, 2);
insert into base_guess (guess, whitewalker, guess_id) values('f', 'f', 36);
insert into guess(question_id, person_id) values(5, 2);
insert into base_guess (guess, whitewalker, guess_id) values('f', 't', 37);
insert into guess(question_id, person_id) values(6, 2);
insert into base_guess (guess, whitewalker, guess_id) values('f', 't', 38);
insert into guess(question_id, person_id) values(7, 2);
insert into base_guess (guess, whitewalker, guess_id) values('t', 'f', 39);
insert into guess(question_id, person_id) values(8, 2);
insert into base_guess (guess, whitewalker, guess_id) values('t', 'f', 40);
insert into guess(question_id, person_id) values(9, 2);
insert into base_guess (guess, whitewalker, guess_id) values('f', 't', 41);
insert into guess(question_id, person_id) values(10, 2);
insert into base_guess (guess, whitewalker, guess_id) values('f', 'f', 42);
insert into guess(question_id, person_id) values(11, 2);
insert into base_guess (guess, whitewalker, guess_id) values('t', 'f', 43);
insert into guess(question_id, person_id) values(12, 2);
insert into base_guess (guess, whitewalker, guess_id) values('f', 'f', 44);
insert into guess(question_id, person_id) values(13, 2);
insert into base_guess (guess, whitewalker, guess_id) values('f', 'f', 45);
insert into guess(question_id, person_id) values(14, 2);
insert into base_guess (guess, whitewalker, guess_id) values('f', 't', 46);
insert into guess(question_id, person_id) values(15, 2);
insert into base_guess (guess, whitewalker, guess_id) values('t', 'f', 47);
insert into guess(question_id, person_id) values(16, 2);
insert into base_guess (guess, whitewalker, guess_id) values('f', 'f', 48);
insert into guess(question_id, person_id) values(17, 2);
insert into base_guess (guess, whitewalker, guess_id) values('t', 'f', 49);
insert into guess(question_id, person_id) values(18, 2);
insert into base_guess (guess, whitewalker, guess_id) values('t', 'f', 50);
insert into guess(question_id, person_id) values(19, 2);
insert into base_guess (guess, whitewalker, guess_id) values('f', 'f', 51);
insert into guess(question_id, person_id) values(20, 2);
insert into base_guess (guess, whitewalker, guess_id) values('t', 'f', 52);
insert into guess(question_id, person_id) values(21, 2);
insert into base_guess (guess, whitewalker, guess_id) values('f', 't', 53);
insert into guess(question_id, person_id) values(22, 2);
insert into base_guess (guess, whitewalker, guess_id) values('f', 't', 54);
insert into guess(question_id, person_id) values(23, 2);
insert into base_guess (guess, whitewalker, guess_id) values('f', 't', 55);
insert into guess(question_id, person_id) values(24, 2);
insert into base_guess (guess, whitewalker, guess_id) values('f', 't', 56);
insert into guess(question_id, person_id) values(25, 2);
insert into base_guess (guess, whitewalker, guess_id) values('t', 'f', 57);
insert into guess(question_id, person_id) values(26, 2);
insert into base_guess (guess, whitewalker, guess_id) values('f', 'f', 58);
insert into guess(question_id, person_id) values(27, 2);
insert into base_guess (guess, whitewalker, guess_id) values('t', 'f', 59);
insert into guess(question_id, person_id) values(28, 2);
insert into bonus_guess (guess, guess_id) values('Yes', 60);
insert into guess(question_id, person_id) values(29, 2);
insert into bonus_guess (guess, guess_id) values('No', 61);
insert into guess(question_id, person_id) values(30, 2);
insert into bonus_guess (guess, guess_id) values('Tyrion Lannister', 62);
insert into guess(question_id, person_id) values(31, 2);
insert into bonus_guess (guess, guess_id) values('Strangled', 63);
insert into guess(question_id, person_id) values(32, 2);
insert into bonus_guess (guess, guess_id) values('Sansa Stark', 64);


/*
 * Insert guesses for Gerður Mekkín Gunnarsdóttir
 */
insert into guess(question_id, person_id) values(1, 3);
insert into base_guess (guess, whitewalker, guess_id) values('f', 'f', 65);
insert into guess(question_id, person_id) values(2, 3);
insert into base_guess (guess, whitewalker, guess_id) values('t', 'f', 66);
insert into guess(question_id, person_id) values(3, 3);
insert into base_guess (guess, whitewalker, guess_id) values('t', 'f', 67);
insert into guess(question_id, person_id) values(4, 3);
insert into base_guess (guess, whitewalker, guess_id) values('t', 'f', 68);
insert into guess(question_id, person_id) values(5, 3);
insert into base_guess (guess, whitewalker, guess_id) values('f', 'f', 69);
insert into guess(question_id, person_id) values(6, 3);
insert into base_guess (guess, whitewalker, guess_id) values('f', 'f', 70);
insert into guess(question_id, person_id) values(7, 3);
insert into base_guess (guess, whitewalker, guess_id) values('t', 'f', 71);
insert into guess(question_id, person_id) values(8, 3);
insert into base_guess (guess, whitewalker, guess_id) values('f', 'f', 72);
insert into guess(question_id, person_id) values(9, 3);
insert into base_guess (guess, whitewalker, guess_id) values('f', 'f', 73);
insert into guess(question_id, person_id) values(10, 3);
insert into base_guess (guess, whitewalker, guess_id) values('f', 'f', 74);
insert into guess(question_id, person_id) values(11, 3);
insert into base_guess (guess, whitewalker, guess_id) values('t', 'f', 75);
insert into guess(question_id, person_id) values(12, 3);
insert into base_guess (guess, whitewalker, guess_id) values('f', 't', 76);
insert into guess(question_id, person_id) values(13, 3);
insert into base_guess (guess, whitewalker, guess_id) values('f', 'f', 77);
insert into guess(question_id, person_id) values(14, 3);
insert into base_guess (guess, whitewalker, guess_id) values('f', 'f', 78);
insert into guess(question_id, person_id) values(15, 3);
insert into base_guess (guess, whitewalker, guess_id) values('t', 'f', 79);
insert into guess(question_id, person_id) values(16, 3);
insert into base_guess (guess, whitewalker, guess_id) values('t', 'f', 80);
insert into guess(question_id, person_id) values(17, 3);
insert into base_guess (guess, whitewalker, guess_id) values('t', 'f', 81);
insert into guess(question_id, person_id) values(18, 3);
insert into base_guess (guess, whitewalker, guess_id) values('f', 'f', 82);
insert into guess(question_id, person_id) values(19, 3);
insert into base_guess (guess, whitewalker, guess_id) values('f', 'f', 83);
insert into guess(question_id, person_id) values(20, 3);
insert into base_guess (guess, whitewalker, guess_id) values('f', 'f', 84);
insert into guess(question_id, person_id) values(21, 3);
insert into base_guess (guess, whitewalker, guess_id) values('t', 'f', 85);
insert into guess(question_id, person_id) values(22, 3);
insert into base_guess (guess, whitewalker, guess_id) values('t', 'f', 86);
insert into guess(question_id, person_id) values(23, 3);
insert into base_guess (guess, whitewalker, guess_id) values('f', 'f', 87);
insert into guess(question_id, person_id) values(24, 3);
insert into base_guess (guess, whitewalker, guess_id) values('f', 'f', 88);
insert into guess(question_id, person_id) values(25, 3);
insert into base_guess (guess, whitewalker, guess_id) values('t', 'f', 89);
insert into guess(question_id, person_id) values(26, 3);
insert into base_guess (guess, whitewalker, guess_id) values('f', 'f', 90);
insert into guess(question_id, person_id) values(27, 3);
insert into base_guess (guess, whitewalker, guess_id) values('f', 'f', 91);
insert into guess(question_id, person_id) values(28, 3);
insert into bonus_guess (guess, guess_id) values('No', 92);
insert into guess(question_id, person_id) values(29, 3);
insert into bonus_guess (guess, guess_id) values('Yes', 93);
insert into guess(question_id, person_id) values(30, 3);
insert into bonus_guess (guess, guess_id) values('Drogon', 94);
insert into guess(question_id, person_id) values(31, 3);
insert into bonus_guess (guess, guess_id) values('Eaten by dragon', 95);
insert into guess(question_id, person_id) values(32, 3);
insert into bonus_guess (guess, guess_id) values('Sansa Stark', 96);


/*
 * Insert guesses for Haffi
 */
insert into guess(question_id, person_id) values(1, 4);
insert into base_guess (guess, whitewalker, guess_id) values('f', 't', 97);
insert into guess(question_id, person_id) values(2, 4);
insert into base_guess (guess, whitewalker, guess_id) values('t', 'f', 98);
insert into guess(question_id, person_id) values(3, 4);
insert into base_guess (guess, whitewalker, guess_id) values('t', 'f', 99);
insert into guess(question_id, person_id) values(4, 4);
insert into base_guess (guess, whitewalker, guess_id) values('f', 'f', 100);
insert into guess(question_id, person_id) values(5, 4);
insert into base_guess (guess, whitewalker, guess_id) values('f', 'f', 101);
insert into guess(question_id, person_id) values(6, 4);
insert into base_guess (guess, whitewalker, guess_id) values('f', 'f', 102);
insert into guess(question_id, person_id) values(7, 4);
insert into base_guess (guess, whitewalker, guess_id) values('f', 'f', 103);
insert into guess(question_id, person_id) values(8, 4);
insert into base_guess (guess, whitewalker, guess_id) values('t', 'f', 104);
insert into guess(question_id, person_id) values(9, 4);
insert into base_guess (guess, whitewalker, guess_id) values('f', 'f', 105);
insert into guess(question_id, person_id) values(10, 4);
insert into base_guess (guess, whitewalker, guess_id) values('t', 'f', 106);
insert into guess(question_id, person_id) values(11, 4);
insert into base_guess (guess, whitewalker, guess_id) values('f', 'f', 107);
insert into guess(question_id, person_id) values(12, 4);
insert into base_guess (guess, whitewalker, guess_id) values('t', 'f', 108);
insert into guess(question_id, person_id) values(13, 4);
insert into base_guess (guess, whitewalker, guess_id) values('f', 'f', 109);
insert into guess(question_id, person_id) values(14, 4);
insert into base_guess (guess, whitewalker, guess_id) values('f', 'f', 110);
insert into guess(question_id, person_id) values(15, 4);
insert into base_guess (guess, whitewalker, guess_id) values('t', 'f', 111);
insert into guess(question_id, person_id) values(16, 4);
insert into base_guess (guess, whitewalker, guess_id) values('t', 'f', 112);
insert into guess(question_id, person_id) values(17, 4);
insert into base_guess (guess, whitewalker, guess_id) values('t', 'f', 113);
insert into guess(question_id, person_id) values(18, 4);
insert into base_guess (guess, whitewalker, guess_id) values('t', 'f', 114);
insert into guess(question_id, person_id) values(19, 4);
insert into base_guess (guess, whitewalker, guess_id) values('f', 'f', 115);
insert into guess(question_id, person_id) values(20, 4);
insert into base_guess (guess, whitewalker, guess_id) values('t', 'f', 116);
insert into guess(question_id, person_id) values(21, 4);
insert into base_guess (guess, whitewalker, guess_id) values('t', 'f', 117);
insert into guess(question_id, person_id) values(22, 4);
insert into base_guess (guess, whitewalker, guess_id) values('t', 'f', 118);
insert into guess(question_id, person_id) values(23, 4);
insert into base_guess (guess, whitewalker, guess_id) values('t', 'f', 119);
insert into guess(question_id, person_id) values(24, 4);
insert into base_guess (guess, whitewalker, guess_id) values('f', 'f', 120);
insert into guess(question_id, person_id) values(25, 4);
insert into base_guess (guess, whitewalker, guess_id) values('t', 'f', 121);
insert into guess(question_id, person_id) values(26, 4);
insert into base_guess (guess, whitewalker, guess_id) values('f', 'f', 122);
insert into guess(question_id, person_id) values(27, 4);
insert into base_guess (guess, whitewalker, guess_id) values('t', 'f', 123);
insert into guess(question_id, person_id) values(28, 4);
insert into bonus_guess (guess, guess_id) values('No', 124);
insert into guess(question_id, person_id) values(29, 4);
insert into bonus_guess (guess, guess_id) values('Yes', 125);
insert into guess(question_id, person_id) values(30, 4);
insert into bonus_guess (guess, guess_id) values('Arya Stark', 126);
insert into guess(question_id, person_id) values(31, 4);
insert into bonus_guess (guess, guess_id) values('Aryas weapon', 127);
insert into guess(question_id, person_id) values(32, 4);
insert into bonus_guess (guess, guess_id) values('Daenerys Targaryen', 128);


/*
 * Insert guesses for Hafsteinn Sigmarsson
 */
insert into guess(question_id, person_id) values(1, 5);
insert into base_guess (guess, whitewalker, guess_id) values('t', 'f', 129);
insert into guess(question_id, person_id) values(2, 5);
insert into base_guess (guess, whitewalker, guess_id) values('t', 'f', 130);
insert into guess(question_id, person_id) values(3, 5);
insert into base_guess (guess, whitewalker, guess_id) values('t', 'f', 131);
insert into guess(question_id, person_id) values(4, 5);
insert into base_guess (guess, whitewalker, guess_id) values('t', 'f', 132);
insert into guess(question_id, person_id) values(5, 5);
insert into base_guess (guess, whitewalker, guess_id) values('f', 'f', 133);
insert into guess(question_id, person_id) values(6, 5);
insert into base_guess (guess, whitewalker, guess_id) values('t', 'f', 134);
insert into guess(question_id, person_id) values(7, 5);
insert into base_guess (guess, whitewalker, guess_id) values('t', 'f', 135);
insert into guess(question_id, person_id) values(8, 5);
insert into base_guess (guess, whitewalker, guess_id) values('t', 'f', 136);
insert into guess(question_id, person_id) values(9, 5);
insert into base_guess (guess, whitewalker, guess_id) values('f', 'f', 137);
insert into guess(question_id, person_id) values(10, 5);
insert into base_guess (guess, whitewalker, guess_id) values('t', 'f', 138);
insert into guess(question_id, person_id) values(11, 5);
insert into base_guess (guess, whitewalker, guess_id) values('f', 'f', 139);
insert into guess(question_id, person_id) values(12, 5);
insert into base_guess (guess, whitewalker, guess_id) values('f', 'f', 140);
insert into guess(question_id, person_id) values(13, 5);
insert into base_guess (guess, whitewalker, guess_id) values('t', 'f', 141);
insert into guess(question_id, person_id) values(14, 5);
insert into base_guess (guess, whitewalker, guess_id) values('f', 'f', 142);
insert into guess(question_id, person_id) values(15, 5);
insert into base_guess (guess, whitewalker, guess_id) values('t', 'f', 143);
insert into guess(question_id, person_id) values(16, 5);
insert into base_guess (guess, whitewalker, guess_id) values('t', 'f', 144);
insert into guess(question_id, person_id) values(17, 5);
insert into base_guess (guess, whitewalker, guess_id) values('t', 'f', 145);
insert into guess(question_id, person_id) values(18, 5);
insert into base_guess (guess, whitewalker, guess_id) values('f', 'f', 146);
insert into guess(question_id, person_id) values(19, 5);
insert into base_guess (guess, whitewalker, guess_id) values('t', 'f', 147);
insert into guess(question_id, person_id) values(20, 5);
insert into base_guess (guess, whitewalker, guess_id) values('f', 'f', 148);
insert into guess(question_id, person_id) values(21, 5);
insert into base_guess (guess, whitewalker, guess_id) values('t', 'f', 149);
insert into guess(question_id, person_id) values(22, 5);
insert into base_guess (guess, whitewalker, guess_id) values('t', 'f', 150);
insert into guess(question_id, person_id) values(23, 5);
insert into base_guess (guess, whitewalker, guess_id) values('t', 'f', 151);
insert into guess(question_id, person_id) values(24, 5);
insert into base_guess (guess, whitewalker, guess_id) values('f', 'f', 152);
insert into guess(question_id, person_id) values(25, 5);
insert into base_guess (guess, whitewalker, guess_id) values('t', 'f', 153);
insert into guess(question_id, person_id) values(26, 5);
insert into base_guess (guess, whitewalker, guess_id) values('f', 'f', 154);
insert into guess(question_id, person_id) values(27, 5);
insert into base_guess (guess, whitewalker, guess_id) values('f', 'f', 155);
insert into guess(question_id, person_id) values(28, 5);
insert into bonus_guess (guess, guess_id) values('Yes', 156);
insert into guess(question_id, person_id) values(29, 5);
insert into bonus_guess (guess, guess_id) values('Yes', 157);
insert into guess(question_id, person_id) values(30, 5);
insert into bonus_guess (guess, guess_id) values('Samwell Tarly', 158);
insert into guess(question_id, person_id) values(31, 5);
insert into bonus_guess (guess, guess_id) values('Dragon Glass', 159);
insert into guess(question_id, person_id) values(32, 5);
insert into bonus_guess (guess, guess_id) values('Daenerys Targaryen', 160);


/*
 * Insert guesses for Lena Hulda
 */
insert into guess(question_id, person_id) values(1, 6);
insert into base_guess (guess, whitewalker, guess_id) values('t', 'f', 161);
insert into guess(question_id, person_id) values(2, 6);
insert into base_guess (guess, whitewalker, guess_id) values('t', 'f', 162);
insert into guess(question_id, person_id) values(3, 6);
insert into base_guess (guess, whitewalker, guess_id) values('t', 'f', 163);
insert into guess(question_id, person_id) values(4, 6);
insert into base_guess (guess, whitewalker, guess_id) values('t', 'f', 164);
insert into guess(question_id, person_id) values(5, 6);
insert into base_guess (guess, whitewalker, guess_id) values('t', 'f', 165);
insert into guess(question_id, person_id) values(6, 6);
insert into base_guess (guess, whitewalker, guess_id) values('f', 't', 166);
insert into guess(question_id, person_id) values(7, 6);
insert into base_guess (guess, whitewalker, guess_id) values('f', 'f', 167);
insert into guess(question_id, person_id) values(8, 6);
insert into base_guess (guess, whitewalker, guess_id) values('f', 'f', 168);
insert into guess(question_id, person_id) values(9, 6);
insert into base_guess (guess, whitewalker, guess_id) values('t', 'f', 169);
insert into guess(question_id, person_id) values(10, 6);
insert into base_guess (guess, whitewalker, guess_id) values('f', 'f', 170);
insert into guess(question_id, person_id) values(11, 6);
insert into base_guess (guess, whitewalker, guess_id) values('t', 'f', 171);
insert into guess(question_id, person_id) values(12, 6);
insert into base_guess (guess, whitewalker, guess_id) values('t', 'f', 172);
insert into guess(question_id, person_id) values(13, 6);
insert into base_guess (guess, whitewalker, guess_id) values('f', 't', 173);
insert into guess(question_id, person_id) values(14, 6);
insert into base_guess (guess, whitewalker, guess_id) values('f', 'f', 174);
insert into guess(question_id, person_id) values(15, 6);
insert into base_guess (guess, whitewalker, guess_id) values('t', 'f', 175);
insert into guess(question_id, person_id) values(16, 6);
insert into base_guess (guess, whitewalker, guess_id) values('t', 'f', 176);
insert into guess(question_id, person_id) values(17, 6);
insert into base_guess (guess, whitewalker, guess_id) values('f', 't', 177);
insert into guess(question_id, person_id) values(18, 6);
insert into base_guess (guess, whitewalker, guess_id) values('f', 'f', 178);
insert into guess(question_id, person_id) values(19, 6);
insert into base_guess (guess, whitewalker, guess_id) values('t', 'f', 179);
insert into guess(question_id, person_id) values(20, 6);
insert into base_guess (guess, whitewalker, guess_id) values('f', 'f', 180);
insert into guess(question_id, person_id) values(21, 6);
insert into base_guess (guess, whitewalker, guess_id) values('t', 'f', 181);
insert into guess(question_id, person_id) values(22, 6);
insert into base_guess (guess, whitewalker, guess_id) values('f', 't', 182);
insert into guess(question_id, person_id) values(23, 6);
insert into base_guess (guess, whitewalker, guess_id) values('f', 't', 183);
insert into guess(question_id, person_id) values(24, 6);
insert into base_guess (guess, whitewalker, guess_id) values('f', 'f', 184);
insert into guess(question_id, person_id) values(25, 6);
insert into base_guess (guess, whitewalker, guess_id) values('f', 'f', 185);
insert into guess(question_id, person_id) values(26, 6);
insert into base_guess (guess, whitewalker, guess_id) values('t', 'f', 186);
insert into guess(question_id, person_id) values(27, 6);
insert into base_guess (guess, whitewalker, guess_id) values('f', 'f', 187);
insert into guess(question_id, person_id) values(28, 6);
insert into bonus_guess (guess, guess_id) values('No', 188);
insert into guess(question_id, person_id) values(29, 6);
insert into bonus_guess (guess, guess_id) values('No', 189);
insert into guess(question_id, person_id) values(30, 6);
insert into bonus_guess (guess, guess_id) values('Arya Stark', 190);
insert into guess(question_id, person_id) values(31, 6);
insert into bonus_guess (guess, guess_id) values('Aryas weapon', 191);
insert into guess(question_id, person_id) values(32, 6);
insert into bonus_guess (guess, guess_id) values('Sansa Stark', 192);


/*
 * Insert guesses for Magnús G. Hilmarsson
 */
insert into guess(question_id, person_id) values(1, 7);
insert into base_guess (guess, whitewalker, guess_id) values('t', 'f', 193);
insert into guess(question_id, person_id) values(2, 7);
insert into base_guess (guess, whitewalker, guess_id) values('t', 'f', 194);
insert into guess(question_id, person_id) values(3, 7);
insert into base_guess (guess, whitewalker, guess_id) values('f', 'f', 195);
insert into guess(question_id, person_id) values(4, 7);
insert into base_guess (guess, whitewalker, guess_id) values('f', 'f', 196);
insert into guess(question_id, person_id) values(5, 7);
insert into base_guess (guess, whitewalker, guess_id) values('f', 'f', 197);
insert into guess(question_id, person_id) values(6, 7);
insert into base_guess (guess, whitewalker, guess_id) values('t', 'f', 198);
insert into guess(question_id, person_id) values(7, 7);
insert into base_guess (guess, whitewalker, guess_id) values('t', 'f', 199);
insert into guess(question_id, person_id) values(8, 7);
insert into base_guess (guess, whitewalker, guess_id) values('f', 'f', 200);
insert into guess(question_id, person_id) values(9, 7);
insert into base_guess (guess, whitewalker, guess_id) values('t', 't', 201);
insert into guess(question_id, person_id) values(10, 7);
insert into base_guess (guess, whitewalker, guess_id) values('f', 't', 202);
insert into guess(question_id, person_id) values(11, 7);
insert into base_guess (guess, whitewalker, guess_id) values('t', 'f', 203);
insert into guess(question_id, person_id) values(12, 7);
insert into base_guess (guess, whitewalker, guess_id) values('f', 't', 204);
insert into guess(question_id, person_id) values(13, 7);
insert into base_guess (guess, whitewalker, guess_id) values('f', 'f', 205);
insert into guess(question_id, person_id) values(14, 7);
insert into base_guess (guess, whitewalker, guess_id) values('f', 'f', 206);
insert into guess(question_id, person_id) values(15, 7);
insert into base_guess (guess, whitewalker, guess_id) values('t', 'f', 207);
insert into guess(question_id, person_id) values(16, 7);
insert into base_guess (guess, whitewalker, guess_id) values('t', 'f', 208);
insert into guess(question_id, person_id) values(17, 7);
insert into base_guess (guess, whitewalker, guess_id) values('t', 'f', 209);
insert into guess(question_id, person_id) values(18, 7);
insert into base_guess (guess, whitewalker, guess_id) values('f', 'f', 210);
insert into guess(question_id, person_id) values(19, 7);
insert into base_guess (guess, whitewalker, guess_id) values('f', 't', 211);
insert into guess(question_id, person_id) values(20, 7);
insert into base_guess (guess, whitewalker, guess_id) values('f', 't', 212);
insert into guess(question_id, person_id) values(21, 7);
insert into base_guess (guess, whitewalker, guess_id) values('t', 'f', 213);
insert into guess(question_id, person_id) values(22, 7);
insert into base_guess (guess, whitewalker, guess_id) values('f', 't', 214);
insert into guess(question_id, person_id) values(23, 7);
insert into base_guess (guess, whitewalker, guess_id) values('f', 't', 215);
insert into guess(question_id, person_id) values(24, 7);
insert into base_guess (guess, whitewalker, guess_id) values('f', 'f', 216);
insert into guess(question_id, person_id) values(25, 7);
insert into base_guess (guess, whitewalker, guess_id) values('f', 'f', 217);
insert into guess(question_id, person_id) values(26, 7);
insert into base_guess (guess, whitewalker, guess_id) values('f', 'f', 218);
insert into guess(question_id, person_id) values(27, 7);
insert into base_guess (guess, whitewalker, guess_id) values('f', 't', 219);
insert into guess(question_id, person_id) values(28, 7);
insert into bonus_guess (guess, guess_id) values('Yes', 220);
insert into guess(question_id, person_id) values(29, 7);
insert into bonus_guess (guess, guess_id) values('Yes', 221);
insert into guess(question_id, person_id) values(30, 7);
insert into bonus_guess (guess, guess_id) values('Bran Stark', 222);
insert into guess(question_id, person_id) values(31, 7);
insert into bonus_guess (guess, guess_id) values('', 223);
insert into guess(question_id, person_id) values(32, 7);
insert into bonus_guess (guess, guess_id) values('Jon Snow', 224);


/*
 * Insert guesses for Sandra Rós Hrefnu Jónsdóttir
 */
insert into guess(question_id, person_id) values(1, 8);
insert into base_guess (guess, whitewalker, guess_id) values('f', 't', 225);
insert into guess(question_id, person_id) values(2, 8);
insert into base_guess (guess, whitewalker, guess_id) values('f', 'f', 226);
insert into guess(question_id, person_id) values(3, 8);
insert into base_guess (guess, whitewalker, guess_id) values('t', 'f', 227);
insert into guess(question_id, person_id) values(4, 8);
insert into base_guess (guess, whitewalker, guess_id) values('f', 'f', 228);
insert into guess(question_id, person_id) values(5, 8);
insert into base_guess (guess, whitewalker, guess_id) values('f', 'f', 229);
insert into guess(question_id, person_id) values(6, 8);
insert into base_guess (guess, whitewalker, guess_id) values('t', 'f', 230);
insert into guess(question_id, person_id) values(7, 8);
insert into base_guess (guess, whitewalker, guess_id) values('t', 'f', 231);
insert into guess(question_id, person_id) values(8, 8);
insert into base_guess (guess, whitewalker, guess_id) values('t', 'f', 232);
insert into guess(question_id, person_id) values(9, 8);
insert into base_guess (guess, whitewalker, guess_id) values('f', 't', 233);
insert into guess(question_id, person_id) values(10, 8);
insert into base_guess (guess, whitewalker, guess_id) values('t', 'f', 234);
insert into guess(question_id, person_id) values(11, 8);
insert into base_guess (guess, whitewalker, guess_id) values('f', 'f', 235);
insert into guess(question_id, person_id) values(12, 8);
insert into base_guess (guess, whitewalker, guess_id) values('f', 't', 236);
insert into guess(question_id, person_id) values(13, 8);
insert into base_guess (guess, whitewalker, guess_id) values('f', 't', 237);
insert into guess(question_id, person_id) values(14, 8);
insert into base_guess (guess, whitewalker, guess_id) values('f', 't', 238);
insert into guess(question_id, person_id) values(15, 8);
insert into base_guess (guess, whitewalker, guess_id) values('f', 'f', 239);
insert into guess(question_id, person_id) values(16, 8);
insert into base_guess (guess, whitewalker, guess_id) values('f', 'f', 240);
insert into guess(question_id, person_id) values(17, 8);
insert into base_guess (guess, whitewalker, guess_id) values('t', 'f', 241);
insert into guess(question_id, person_id) values(18, 8);
insert into base_guess (guess, whitewalker, guess_id) values('t', 'f', 242);
insert into guess(question_id, person_id) values(19, 8);
insert into base_guess (guess, whitewalker, guess_id) values('t', 'f', 243);
insert into guess(question_id, person_id) values(20, 8);
insert into base_guess (guess, whitewalker, guess_id) values('f', 'f', 244);
insert into guess(question_id, person_id) values(21, 8);
insert into base_guess (guess, whitewalker, guess_id) values('f', 't', 245);
insert into guess(question_id, person_id) values(22, 8);
insert into base_guess (guess, whitewalker, guess_id) values('f', 't', 246);
insert into guess(question_id, person_id) values(23, 8);
insert into base_guess (guess, whitewalker, guess_id) values('f', 't', 247);
insert into guess(question_id, person_id) values(24, 8);
insert into base_guess (guess, whitewalker, guess_id) values('f', 't', 248);
insert into guess(question_id, person_id) values(25, 8);
insert into base_guess (guess, whitewalker, guess_id) values('f', 'f', 249);
insert into guess(question_id, person_id) values(26, 8);
insert into base_guess (guess, whitewalker, guess_id) values('f', 'f', 250);
insert into guess(question_id, person_id) values(27, 8);
insert into base_guess (guess, whitewalker, guess_id) values('f', 'f', 251);
insert into guess(question_id, person_id) values(28, 8);
insert into bonus_guess (guess, guess_id) values('Yes', 252);
insert into guess(question_id, person_id) values(29, 8);
insert into bonus_guess (guess, guess_id) values('No', 253);
insert into guess(question_id, person_id) values(30, 8);
insert into bonus_guess (guess, guess_id) values('Bran Stark', 254);
insert into guess(question_id, person_id) values(31, 8);
insert into bonus_guess (guess, guess_id) values('Magic', 255);
insert into guess(question_id, person_id) values(32, 8);
insert into bonus_guess (guess, guess_id) values('No one', 256);


/*
 * Insert guesses for Smári Ívarsson
 */
insert into guess(question_id, person_id) values(1, 9);
insert into base_guess (guess, whitewalker, guess_id) values('f', 'f', 257);
insert into guess(question_id, person_id) values(2, 9);
insert into base_guess (guess, whitewalker, guess_id) values('t', 'f', 258);
insert into guess(question_id, person_id) values(3, 9);
insert into base_guess (guess, whitewalker, guess_id) values('t', 'f', 259);
insert into guess(question_id, person_id) values(4, 9);
insert into base_guess (guess, whitewalker, guess_id) values('t', 'f', 260);
insert into guess(question_id, person_id) values(5, 9);
insert into base_guess (guess, whitewalker, guess_id) values('f', 'f', 261);
insert into guess(question_id, person_id) values(6, 9);
insert into base_guess (guess, whitewalker, guess_id) values('f', 't', 262);
insert into guess(question_id, person_id) values(7, 9);
insert into base_guess (guess, whitewalker, guess_id) values('f', 'f', 263);
insert into guess(question_id, person_id) values(8, 9);
insert into base_guess (guess, whitewalker, guess_id) values('t', 'f', 264);
insert into guess(question_id, person_id) values(9, 9);
insert into base_guess (guess, whitewalker, guess_id) values('t', 't', 265);
insert into guess(question_id, person_id) values(10, 9);
insert into base_guess (guess, whitewalker, guess_id) values('f', 'f', 266);
insert into guess(question_id, person_id) values(11, 9);
insert into base_guess (guess, whitewalker, guess_id) values('f', 'f', 267);
insert into guess(question_id, person_id) values(12, 9);
insert into base_guess (guess, whitewalker, guess_id) values('t', 'f', 268);
insert into guess(question_id, person_id) values(13, 9);
insert into base_guess (guess, whitewalker, guess_id) values('f', 't', 269);
insert into guess(question_id, person_id) values(14, 9);
insert into base_guess (guess, whitewalker, guess_id) values('f', 'f', 270);
insert into guess(question_id, person_id) values(15, 9);
insert into base_guess (guess, whitewalker, guess_id) values('t', 'f', 271);
insert into guess(question_id, person_id) values(16, 9);
insert into base_guess (guess, whitewalker, guess_id) values('t', 'f', 272);
insert into guess(question_id, person_id) values(17, 9);
insert into base_guess (guess, whitewalker, guess_id) values('t', 'f', 273);
insert into guess(question_id, person_id) values(18, 9);
insert into base_guess (guess, whitewalker, guess_id) values('f', 'f', 274);
insert into guess(question_id, person_id) values(19, 9);
insert into base_guess (guess, whitewalker, guess_id) values('f', 'f', 275);
insert into guess(question_id, person_id) values(20, 9);
insert into base_guess (guess, whitewalker, guess_id) values('f', 'f', 276);
insert into guess(question_id, person_id) values(21, 9);
insert into base_guess (guess, whitewalker, guess_id) values('f', 'f', 277);
insert into guess(question_id, person_id) values(22, 9);
insert into base_guess (guess, whitewalker, guess_id) values('t', 'f', 278);
insert into guess(question_id, person_id) values(23, 9);
insert into base_guess (guess, whitewalker, guess_id) values('t', 'f', 279);
insert into guess(question_id, person_id) values(24, 9);
insert into base_guess (guess, whitewalker, guess_id) values('t', 'f', 280);
insert into guess(question_id, person_id) values(25, 9);
insert into base_guess (guess, whitewalker, guess_id) values('f', 'f', 281);
insert into guess(question_id, person_id) values(26, 9);
insert into base_guess (guess, whitewalker, guess_id) values('f', 'f', 282);
insert into guess(question_id, person_id) values(27, 9);
insert into base_guess (guess, whitewalker, guess_id) values('f', 'f', 283);
insert into guess(question_id, person_id) values(28, 9);
insert into bonus_guess (guess, guess_id) values('Yes', 284);
insert into guess(question_id, person_id) values(29, 9);
insert into bonus_guess (guess, guess_id) values('No', 285);
insert into guess(question_id, person_id) values(30, 9);
insert into bonus_guess (guess, guess_id) values('Jon Snow', 286);
insert into guess(question_id, person_id) values(31, 9);
insert into bonus_guess (guess, guess_id) values('Lightbringer', 287);
insert into guess(question_id, person_id) values(32, 9);
insert into bonus_guess (guess, guess_id) values('Daenerys Targaryen', 288);


/*
 * Insert guesses for Örvar Guttormsson
 */
insert into guess(question_id, person_id) values(1, 10);
insert into base_guess (guess, whitewalker, guess_id) values('t', 'f', 289);
insert into guess(question_id, person_id) values(2, 10);
insert into base_guess (guess, whitewalker, guess_id) values('t', 'f', 290);
insert into guess(question_id, person_id) values(3, 10);
insert into base_guess (guess, whitewalker, guess_id) values('t', 'f', 291);
insert into guess(question_id, person_id) values(4, 10);
insert into base_guess (guess, whitewalker, guess_id) values('f', 't', 292);
insert into guess(question_id, person_id) values(5, 10);
insert into base_guess (guess, whitewalker, guess_id) values('f', 'f', 293);
insert into guess(question_id, person_id) values(6, 10);
insert into base_guess (guess, whitewalker, guess_id) values('t', 'f', 294);
insert into guess(question_id, person_id) values(7, 10);
insert into base_guess (guess, whitewalker, guess_id) values('t', 'f', 295);
insert into guess(question_id, person_id) values(8, 10);
insert into base_guess (guess, whitewalker, guess_id) values('t', 'f', 296);
insert into guess(question_id, person_id) values(9, 10);
insert into base_guess (guess, whitewalker, guess_id) values('t', 't', 297);
insert into guess(question_id, person_id) values(10, 10);
insert into base_guess (guess, whitewalker, guess_id) values('f', 'f', 298);
insert into guess(question_id, person_id) values(11, 10);
insert into base_guess (guess, whitewalker, guess_id) values('f', 't', 299);
insert into guess(question_id, person_id) values(12, 10);
insert into base_guess (guess, whitewalker, guess_id) values('f', 'f', 300);
insert into guess(question_id, person_id) values(13, 10);
insert into base_guess (guess, whitewalker, guess_id) values('f', 'f', 301);
insert into guess(question_id, person_id) values(14, 10);
insert into base_guess (guess, whitewalker, guess_id) values('f', 'f', 302);
insert into guess(question_id, person_id) values(15, 10);
insert into base_guess (guess, whitewalker, guess_id) values('f', 'f', 303);
insert into guess(question_id, person_id) values(16, 10);
insert into base_guess (guess, whitewalker, guess_id) values('t', 'f', 304);
insert into guess(question_id, person_id) values(17, 10);
insert into base_guess (guess, whitewalker, guess_id) values('t', 'f', 305);
insert into guess(question_id, person_id) values(18, 10);
insert into base_guess (guess, whitewalker, guess_id) values('f', 'f', 306);
insert into guess(question_id, person_id) values(19, 10);
insert into base_guess (guess, whitewalker, guess_id) values('t', 'f', 307);
insert into guess(question_id, person_id) values(20, 10);
insert into base_guess (guess, whitewalker, guess_id) values('f', 'f', 308);
insert into guess(question_id, person_id) values(21, 10);
insert into base_guess (guess, whitewalker, guess_id) values('f', 'f', 309);
insert into guess(question_id, person_id) values(22, 10);
insert into base_guess (guess, whitewalker, guess_id) values('f', 't', 310);
insert into guess(question_id, person_id) values(23, 10);
insert into base_guess (guess, whitewalker, guess_id) values('f', 't', 311);
insert into guess(question_id, person_id) values(24, 10);
insert into base_guess (guess, whitewalker, guess_id) values('f', 't', 312);
insert into guess(question_id, person_id) values(25, 10);
insert into base_guess (guess, whitewalker, guess_id) values('f', 'f', 313);
insert into guess(question_id, person_id) values(26, 10);
insert into base_guess (guess, whitewalker, guess_id) values('f', 'f', 314);
insert into guess(question_id, person_id) values(27, 10);
insert into base_guess (guess, whitewalker, guess_id) values('f', 't', 315);
insert into guess(question_id, person_id) values(28, 10);
insert into bonus_guess (guess, guess_id) values('Yes', 316);
insert into guess(question_id, person_id) values(29, 10);
insert into bonus_guess (guess, guess_id) values('No', 317);
insert into guess(question_id, person_id) values(30, 10);
insert into bonus_guess (guess, guess_id) values('Tyrion Lannister', 318);
insert into guess(question_id, person_id) values(31, 10);
insert into bonus_guess (guess, guess_id) values('', 319);
insert into guess(question_id, person_id) values(32, 10);
insert into bonus_guess (guess, guess_id) values('No one', 320);


/*
 * Insert guesses for Bogi Fjalar Sigurðsson
 */
insert into guess(question_id, person_id) values(1, 11);
insert into base_guess (guess, whitewalker, guess_id) values('t', 'f', 321);
insert into guess(question_id, person_id) values(2, 11);
insert into base_guess (guess, whitewalker, guess_id) values('f', 'f', 322);
insert into guess(question_id, person_id) values(3, 11);
insert into base_guess (guess, whitewalker, guess_id) values('f', 'f', 323);
insert into guess(question_id, person_id) values(4, 11);
insert into base_guess (guess, whitewalker, guess_id) values('t', 'f', 324);
insert into guess(question_id, person_id) values(5, 11);
insert into base_guess (guess, whitewalker, guess_id) values('f', 'f', 325);
insert into guess(question_id, person_id) values(6, 11);
insert into base_guess (guess, whitewalker, guess_id) values('f', 'f', 326);
insert into guess(question_id, person_id) values(7, 11);
insert into base_guess (guess, whitewalker, guess_id) values('t', 'f', 327);
insert into guess(question_id, person_id) values(8, 11);
insert into base_guess (guess, whitewalker, guess_id) values('t', 'f', 328);
insert into guess(question_id, person_id) values(9, 11);
insert into base_guess (guess, whitewalker, guess_id) values('f', 'f', 329);
insert into guess(question_id, person_id) values(10, 11);
insert into base_guess (guess, whitewalker, guess_id) values('t', 'f', 330);
insert into guess(question_id, person_id) values(11, 11);
insert into base_guess (guess, whitewalker, guess_id) values('f', 'f', 331);
insert into guess(question_id, person_id) values(12, 11);
insert into base_guess (guess, whitewalker, guess_id) values('t', 'f', 332);
insert into guess(question_id, person_id) values(13, 11);
insert into base_guess (guess, whitewalker, guess_id) values('t', 'f', 333);
insert into guess(question_id, person_id) values(14, 11);
insert into base_guess (guess, whitewalker, guess_id) values('f', 'f', 334);
insert into guess(question_id, person_id) values(15, 11);
insert into base_guess (guess, whitewalker, guess_id) values('t', 'f', 335);
insert into guess(question_id, person_id) values(16, 11);
insert into base_guess (guess, whitewalker, guess_id) values('t', 'f', 336);
insert into guess(question_id, person_id) values(17, 11);
insert into base_guess (guess, whitewalker, guess_id) values('f', 't', 337);
insert into guess(question_id, person_id) values(18, 11);
insert into base_guess (guess, whitewalker, guess_id) values('t', 'f', 338);
insert into guess(question_id, person_id) values(19, 11);
insert into base_guess (guess, whitewalker, guess_id) values('t', 'f', 339);
insert into guess(question_id, person_id) values(20, 11);
insert into base_guess (guess, whitewalker, guess_id) values('t', 'f', 340);
insert into guess(question_id, person_id) values(21, 11);
insert into base_guess (guess, whitewalker, guess_id) values('f', 'f', 341);
insert into guess(question_id, person_id) values(22, 11);
insert into base_guess (guess, whitewalker, guess_id) values('t', 'f', 342);
insert into guess(question_id, person_id) values(23, 11);
insert into base_guess (guess, whitewalker, guess_id) values('t', 'f', 343);
insert into guess(question_id, person_id) values(24, 11);
insert into base_guess (guess, whitewalker, guess_id) values('f', 'f', 344);
insert into guess(question_id, person_id) values(25, 11);
insert into base_guess (guess, whitewalker, guess_id) values('t', 'f', 345);
insert into guess(question_id, person_id) values(26, 11);
insert into base_guess (guess, whitewalker, guess_id) values('t', 'f', 346);
insert into guess(question_id, person_id) values(27, 11);
insert into base_guess (guess, whitewalker, guess_id) values('f', 'f', 347);
insert into guess(question_id, person_id) values(28, 11);
insert into bonus_guess (guess, guess_id) values('Yes', 348);
insert into guess(question_id, person_id) values(29, 11);
insert into bonus_guess (guess, guess_id) values('Yes', 349);
insert into guess(question_id, person_id) values(30, 11);
insert into bonus_guess (guess, guess_id) values('Jon Snow', 350);
insert into guess(question_id, person_id) values(31, 11);
insert into bonus_guess (guess, guess_id) values('Longclaw', 351);
insert into guess(question_id, person_id) values(32, 11);
insert into bonus_guess (guess, guess_id) values('Daenerys Targaryen', 352);


/*
 * Insert guesses for Borga
 */
insert into guess(question_id, person_id) values(1, 12);
insert into base_guess (guess, whitewalker, guess_id) values('t', 'f', 353);
insert into guess(question_id, person_id) values(2, 12);
insert into base_guess (guess, whitewalker, guess_id) values('f', 'f', 354);
insert into guess(question_id, person_id) values(3, 12);
insert into base_guess (guess, whitewalker, guess_id) values('t', 'f', 355);
insert into guess(question_id, person_id) values(4, 12);
insert into base_guess (guess, whitewalker, guess_id) values('t', 'f', 356);
insert into guess(question_id, person_id) values(5, 12);
insert into base_guess (guess, whitewalker, guess_id) values('f', 'f', 357);
insert into guess(question_id, person_id) values(6, 12);
insert into base_guess (guess, whitewalker, guess_id) values('f', 'f', 358);
insert into guess(question_id, person_id) values(7, 12);
insert into base_guess (guess, whitewalker, guess_id) values('f', 'f', 359);
insert into guess(question_id, person_id) values(8, 12);
insert into base_guess (guess, whitewalker, guess_id) values('t', 'f', 360);
insert into guess(question_id, person_id) values(9, 12);
insert into base_guess (guess, whitewalker, guess_id) values('t', 't', 361);
insert into guess(question_id, person_id) values(10, 12);
insert into base_guess (guess, whitewalker, guess_id) values('f', 'f', 362);
insert into guess(question_id, person_id) values(11, 12);
insert into base_guess (guess, whitewalker, guess_id) values('t', 'f', 363);
insert into guess(question_id, person_id) values(12, 12);
insert into base_guess (guess, whitewalker, guess_id) values('f', 't', 364);
insert into guess(question_id, person_id) values(13, 12);
insert into base_guess (guess, whitewalker, guess_id) values('f', 'f', 365);
insert into guess(question_id, person_id) values(14, 12);
insert into base_guess (guess, whitewalker, guess_id) values('f', 'f', 366);
insert into guess(question_id, person_id) values(15, 12);
insert into base_guess (guess, whitewalker, guess_id) values('f', 'f', 367);
insert into guess(question_id, person_id) values(16, 12);
insert into base_guess (guess, whitewalker, guess_id) values('t', 'f', 368);
insert into guess(question_id, person_id) values(17, 12);
insert into base_guess (guess, whitewalker, guess_id) values('t', 'f', 369);
insert into guess(question_id, person_id) values(18, 12);
insert into base_guess (guess, whitewalker, guess_id) values('t', 'f', 370);
insert into guess(question_id, person_id) values(19, 12);
insert into base_guess (guess, whitewalker, guess_id) values('t', 'f', 371);
insert into guess(question_id, person_id) values(20, 12);
insert into base_guess (guess, whitewalker, guess_id) values('f', 't', 372);
insert into guess(question_id, person_id) values(21, 12);
insert into base_guess (guess, whitewalker, guess_id) values('f', 'f', 373);
insert into guess(question_id, person_id) values(22, 12);
insert into base_guess (guess, whitewalker, guess_id) values('t', 'f', 374);
insert into guess(question_id, person_id) values(23, 12);
insert into base_guess (guess, whitewalker, guess_id) values('f', 't', 375);
insert into guess(question_id, person_id) values(24, 12);
insert into base_guess (guess, whitewalker, guess_id) values('f', 'f', 376);
insert into guess(question_id, person_id) values(25, 12);
insert into base_guess (guess, whitewalker, guess_id) values('t', 'f', 377);
insert into guess(question_id, person_id) values(26, 12);
insert into base_guess (guess, whitewalker, guess_id) values('f', 'f', 378);
insert into guess(question_id, person_id) values(27, 12);
insert into base_guess (guess, whitewalker, guess_id) values('f', 'f', 379);
insert into guess(question_id, person_id) values(28, 12);
insert into bonus_guess (guess, guess_id) values('No', 380);
insert into guess(question_id, person_id) values(29, 12);
insert into bonus_guess (guess, guess_id) values('No', 381);
insert into guess(question_id, person_id) values(30, 12);
insert into bonus_guess (guess, guess_id) values('Brienne of Tarth', 382);
insert into guess(question_id, person_id) values(31, 12);
insert into bonus_guess (guess, guess_id) values('', 383);
insert into guess(question_id, person_id) values(32, 12);
insert into bonus_guess (guess, guess_id) values('Daenerys Targaryen', 384);


/*
 * Insert guesses for Guðmundur Stefán
 */
insert into guess(question_id, person_id) values(1, 13);
insert into base_guess (guess, whitewalker, guess_id) values('f', 't', 385);
insert into guess(question_id, person_id) values(2, 13);
insert into base_guess (guess, whitewalker, guess_id) values('t', 'f', 386);
insert into guess(question_id, person_id) values(3, 13);
insert into base_guess (guess, whitewalker, guess_id) values('t', 'f', 387);
insert into guess(question_id, person_id) values(4, 13);
insert into base_guess (guess, whitewalker, guess_id) values('t', 'f', 388);
insert into guess(question_id, person_id) values(5, 13);
insert into base_guess (guess, whitewalker, guess_id) values('f', 't', 389);
insert into guess(question_id, person_id) values(6, 13);
insert into base_guess (guess, whitewalker, guess_id) values('t', 'f', 390);
insert into guess(question_id, person_id) values(7, 13);
insert into base_guess (guess, whitewalker, guess_id) values('t', 'f', 391);
insert into guess(question_id, person_id) values(8, 13);
insert into base_guess (guess, whitewalker, guess_id) values('f', 'f', 392);
insert into guess(question_id, person_id) values(9, 13);
insert into base_guess (guess, whitewalker, guess_id) values('t', 'f', 393);
insert into guess(question_id, person_id) values(10, 13);
insert into base_guess (guess, whitewalker, guess_id) values('f', 'f', 394);
insert into guess(question_id, person_id) values(11, 13);
insert into base_guess (guess, whitewalker, guess_id) values('f', 't', 395);
insert into guess(question_id, person_id) values(12, 13);
insert into base_guess (guess, whitewalker, guess_id) values('f', 'f', 396);
insert into guess(question_id, person_id) values(13, 13);
insert into base_guess (guess, whitewalker, guess_id) values('t', 'f', 397);
insert into guess(question_id, person_id) values(14, 13);
insert into base_guess (guess, whitewalker, guess_id) values('f', 'f', 398);
insert into guess(question_id, person_id) values(15, 13);
insert into base_guess (guess, whitewalker, guess_id) values('t', 'f', 399);
insert into guess(question_id, person_id) values(16, 13);
insert into base_guess (guess, whitewalker, guess_id) values('t', 'f', 400);
insert into guess(question_id, person_id) values(17, 13);
insert into base_guess (guess, whitewalker, guess_id) values('t', 'f', 401);
insert into guess(question_id, person_id) values(18, 13);
insert into base_guess (guess, whitewalker, guess_id) values('f', 'f', 402);
insert into guess(question_id, person_id) values(19, 13);
insert into base_guess (guess, whitewalker, guess_id) values('f', 't', 403);
insert into guess(question_id, person_id) values(20, 13);
insert into base_guess (guess, whitewalker, guess_id) values('f', 'f', 404);
insert into guess(question_id, person_id) values(21, 13);
insert into base_guess (guess, whitewalker, guess_id) values('f', 'f', 405);
insert into guess(question_id, person_id) values(22, 13);
insert into base_guess (guess, whitewalker, guess_id) values('f', 't', 406);
insert into guess(question_id, person_id) values(23, 13);
insert into base_guess (guess, whitewalker, guess_id) values('f', 't', 407);
insert into guess(question_id, person_id) values(24, 13);
insert into base_guess (guess, whitewalker, guess_id) values('f', 'f', 408);
insert into guess(question_id, person_id) values(25, 13);
insert into base_guess (guess, whitewalker, guess_id) values('f', 'f', 409);
insert into guess(question_id, person_id) values(26, 13);
insert into base_guess (guess, whitewalker, guess_id) values('f', 'f', 410);
insert into guess(question_id, person_id) values(27, 13);
insert into base_guess (guess, whitewalker, guess_id) values('f', 't', 411);
insert into guess(question_id, person_id) values(28, 13);
insert into bonus_guess (guess, guess_id) values('Yes', 412);
insert into guess(question_id, person_id) values(29, 13);
insert into bonus_guess (guess, guess_id) values('No', 413);
insert into guess(question_id, person_id) values(30, 13);
insert into bonus_guess (guess, guess_id) values('Arya Stark', 414);
insert into guess(question_id, person_id) values(31, 13);
insert into bonus_guess (guess, guess_id) values('Aryas weapon', 415);
insert into guess(question_id, person_id) values(32, 13);
insert into bonus_guess (guess, guess_id) values('Sansa Stark', 416);


/*
 * Insert guesses for Haukur Þórðarson
 */
insert into guess(question_id, person_id) values(1, 14);
insert into base_guess (guess, whitewalker, guess_id) values('t', 'f', 417);
insert into guess(question_id, person_id) values(2, 14);
insert into base_guess (guess, whitewalker, guess_id) values('t', 'f', 418);
insert into guess(question_id, person_id) values(3, 14);
insert into base_guess (guess, whitewalker, guess_id) values('t', 'f', 419);
insert into guess(question_id, person_id) values(4, 14);
insert into base_guess (guess, whitewalker, guess_id) values('f', 'f', 420);
insert into guess(question_id, person_id) values(5, 14);
insert into base_guess (guess, whitewalker, guess_id) values('f', 'f', 421);
insert into guess(question_id, person_id) values(6, 14);
insert into base_guess (guess, whitewalker, guess_id) values('t', 'f', 422);
insert into guess(question_id, person_id) values(7, 14);
insert into base_guess (guess, whitewalker, guess_id) values('t', 'f', 423);
insert into guess(question_id, person_id) values(8, 14);
insert into base_guess (guess, whitewalker, guess_id) values('t', 'f', 424);
insert into guess(question_id, person_id) values(9, 14);
insert into base_guess (guess, whitewalker, guess_id) values('f', 't', 425);
insert into guess(question_id, person_id) values(10, 14);
insert into base_guess (guess, whitewalker, guess_id) values('f', 'f', 426);
insert into guess(question_id, person_id) values(11, 14);
insert into base_guess (guess, whitewalker, guess_id) values('f', 'f', 427);
insert into guess(question_id, person_id) values(12, 14);
insert into base_guess (guess, whitewalker, guess_id) values('t', 'f', 428);
insert into guess(question_id, person_id) values(13, 14);
insert into base_guess (guess, whitewalker, guess_id) values('t', 'f', 429);
insert into guess(question_id, person_id) values(14, 14);
insert into base_guess (guess, whitewalker, guess_id) values('f', 'f', 430);
insert into guess(question_id, person_id) values(15, 14);
insert into base_guess (guess, whitewalker, guess_id) values('t', 'f', 431);
insert into guess(question_id, person_id) values(16, 14);
insert into base_guess (guess, whitewalker, guess_id) values('t', 'f', 432);
insert into guess(question_id, person_id) values(17, 14);
insert into base_guess (guess, whitewalker, guess_id) values('t', 'f', 433);
insert into guess(question_id, person_id) values(18, 14);
insert into base_guess (guess, whitewalker, guess_id) values('f', 't', 434);
insert into guess(question_id, person_id) values(19, 14);
insert into base_guess (guess, whitewalker, guess_id) values('t', 'f', 435);
insert into guess(question_id, person_id) values(20, 14);
insert into base_guess (guess, whitewalker, guess_id) values('t', 'f', 436);
insert into guess(question_id, person_id) values(21, 14);
insert into base_guess (guess, whitewalker, guess_id) values('f', 't', 437);
insert into guess(question_id, person_id) values(22, 14);
insert into base_guess (guess, whitewalker, guess_id) values('f', 't', 438);
insert into guess(question_id, person_id) values(23, 14);
insert into base_guess (guess, whitewalker, guess_id) values('f', 't', 439);
insert into guess(question_id, person_id) values(24, 14);
insert into base_guess (guess, whitewalker, guess_id) values('t', 'f', 440);
insert into guess(question_id, person_id) values(25, 14);
insert into base_guess (guess, whitewalker, guess_id) values('t', 'f', 441);
insert into guess(question_id, person_id) values(26, 14);
insert into base_guess (guess, whitewalker, guess_id) values('f', 't', 442);
insert into guess(question_id, person_id) values(27, 14);
insert into base_guess (guess, whitewalker, guess_id) values('f', 'f', 443);
insert into guess(question_id, person_id) values(28, 14);
insert into bonus_guess (guess, guess_id) values('Yes', 444);
insert into guess(question_id, person_id) values(29, 14);
insert into bonus_guess (guess, guess_id) values('No', 445);
insert into guess(question_id, person_id) values(30, 14);
insert into bonus_guess (guess, guess_id) values('Jon Snow', 446);
insert into guess(question_id, person_id) values(31, 14);
insert into bonus_guess (guess, guess_id) values('Lightbringer / Heartsbane', 447);
insert into guess(question_id, person_id) values(32, 14);
insert into bonus_guess (guess, guess_id) values('No one', 448);


/*
 * Insert guesses for Símon Pétur Sigurðsson
 */
insert into guess(question_id, person_id) values(1, 15);
insert into base_guess (guess, whitewalker, guess_id) values('t', 'f', 449);
insert into guess(question_id, person_id) values(2, 15);
insert into base_guess (guess, whitewalker, guess_id) values('f', 't', 450);
insert into guess(question_id, person_id) values(3, 15);
insert into base_guess (guess, whitewalker, guess_id) values('t', 'f', 451);
insert into guess(question_id, person_id) values(4, 15);
insert into base_guess (guess, whitewalker, guess_id) values('f', 't', 452);
insert into guess(question_id, person_id) values(5, 15);
insert into base_guess (guess, whitewalker, guess_id) values('f', 't', 453);
insert into guess(question_id, person_id) values(6, 15);
insert into base_guess (guess, whitewalker, guess_id) values('f', 't', 454);
insert into guess(question_id, person_id) values(7, 15);
insert into base_guess (guess, whitewalker, guess_id) values('f', 'f', 455);
insert into guess(question_id, person_id) values(8, 15);
insert into base_guess (guess, whitewalker, guess_id) values('t', 'f', 456);
insert into guess(question_id, person_id) values(9, 15);
insert into base_guess (guess, whitewalker, guess_id) values('t', 't', 457);
insert into guess(question_id, person_id) values(10, 15);
insert into base_guess (guess, whitewalker, guess_id) values('f', 't', 458);
insert into guess(question_id, person_id) values(11, 15);
insert into base_guess (guess, whitewalker, guess_id) values('t', 'f', 459);
insert into guess(question_id, person_id) values(12, 15);
insert into base_guess (guess, whitewalker, guess_id) values('t', 'f', 460);
insert into guess(question_id, person_id) values(13, 15);
insert into base_guess (guess, whitewalker, guess_id) values('t', 'f', 461);
insert into guess(question_id, person_id) values(14, 15);
insert into base_guess (guess, whitewalker, guess_id) values('f', 't', 462);
insert into guess(question_id, person_id) values(15, 15);
insert into base_guess (guess, whitewalker, guess_id) values('t', 'f', 463);
insert into guess(question_id, person_id) values(16, 15);
insert into base_guess (guess, whitewalker, guess_id) values('f', 'f', 464);
insert into guess(question_id, person_id) values(17, 15);
insert into base_guess (guess, whitewalker, guess_id) values('t', 'f', 465);
insert into guess(question_id, person_id) values(18, 15);
insert into base_guess (guess, whitewalker, guess_id) values('f', 't', 466);
insert into guess(question_id, person_id) values(19, 15);
insert into base_guess (guess, whitewalker, guess_id) values('t', 'f', 467);
insert into guess(question_id, person_id) values(20, 15);
insert into base_guess (guess, whitewalker, guess_id) values('t', 'f', 468);
insert into guess(question_id, person_id) values(21, 15);
insert into base_guess (guess, whitewalker, guess_id) values('f', 't', 469);
insert into guess(question_id, person_id) values(22, 15);
insert into base_guess (guess, whitewalker, guess_id) values('f', 't', 470);
insert into guess(question_id, person_id) values(23, 15);
insert into base_guess (guess, whitewalker, guess_id) values('t', 'f', 471);
insert into guess(question_id, person_id) values(24, 15);
insert into base_guess (guess, whitewalker, guess_id) values('f', 't', 472);
insert into guess(question_id, person_id) values(25, 15);
insert into base_guess (guess, whitewalker, guess_id) values('t', 'f', 473);
insert into guess(question_id, person_id) values(26, 15);
insert into base_guess (guess, whitewalker, guess_id) values('t', 'f', 474);
insert into guess(question_id, person_id) values(27, 15);
insert into base_guess (guess, whitewalker, guess_id) values('f', 't', 475);
insert into guess(question_id, person_id) values(28, 15);
insert into bonus_guess (guess, guess_id) values('No', 476);
insert into guess(question_id, person_id) values(29, 15);
insert into bonus_guess (guess, guess_id) values('No', 477);
insert into guess(question_id, person_id) values(30, 15);
insert into bonus_guess (guess, guess_id) values('Jon Snow', 478);
insert into guess(question_id, person_id) values(31, 15);
insert into bonus_guess (guess, guess_id) values('', 479);
insert into guess(question_id, person_id) values(32, 15);
insert into bonus_guess (guess, guess_id) values('Daenerys Targaryen', 480);


/*
 * Insert guesses for Trausti Veigar Hilmarsson
 */
insert into guess(question_id, person_id) values(1, 16);
insert into base_guess (guess, whitewalker, guess_id) values('f', 'f', 481);
insert into guess(question_id, person_id) values(2, 16);
insert into base_guess (guess, whitewalker, guess_id) values('t', 'f', 482);
insert into guess(question_id, person_id) values(3, 16);
insert into base_guess (guess, whitewalker, guess_id) values('f', 'f', 483);
insert into guess(question_id, person_id) values(4, 16);
insert into base_guess (guess, whitewalker, guess_id) values('t', 'f', 484);
insert into guess(question_id, person_id) values(5, 16);
insert into base_guess (guess, whitewalker, guess_id) values('f', 'f', 485);
insert into guess(question_id, person_id) values(6, 16);
insert into base_guess (guess, whitewalker, guess_id) values('f', 'f', 486);
insert into guess(question_id, person_id) values(7, 16);
insert into base_guess (guess, whitewalker, guess_id) values('t', 'f', 487);
insert into guess(question_id, person_id) values(8, 16);
insert into base_guess (guess, whitewalker, guess_id) values('t', 'f', 488);
insert into guess(question_id, person_id) values(9, 16);
insert into base_guess (guess, whitewalker, guess_id) values('f', 'f', 489);
insert into guess(question_id, person_id) values(10, 16);
insert into base_guess (guess, whitewalker, guess_id) values('t', 'f', 490);
insert into guess(question_id, person_id) values(11, 16);
insert into base_guess (guess, whitewalker, guess_id) values('f', 'f', 491);
insert into guess(question_id, person_id) values(12, 16);
insert into base_guess (guess, whitewalker, guess_id) values('f', 'f', 492);
insert into guess(question_id, person_id) values(13, 16);
insert into base_guess (guess, whitewalker, guess_id) values('t', 'f', 493);
insert into guess(question_id, person_id) values(14, 16);
insert into base_guess (guess, whitewalker, guess_id) values('f', 'f', 494);
insert into guess(question_id, person_id) values(15, 16);
insert into base_guess (guess, whitewalker, guess_id) values('t', 'f', 495);
insert into guess(question_id, person_id) values(16, 16);
insert into base_guess (guess, whitewalker, guess_id) values('f', 'f', 496);
insert into guess(question_id, person_id) values(17, 16);
insert into base_guess (guess, whitewalker, guess_id) values('t', 'f', 497);
insert into guess(question_id, person_id) values(18, 16);
insert into base_guess (guess, whitewalker, guess_id) values('f', 'f', 498);
insert into guess(question_id, person_id) values(19, 16);
insert into base_guess (guess, whitewalker, guess_id) values('t', 'f', 499);
insert into guess(question_id, person_id) values(20, 16);
insert into base_guess (guess, whitewalker, guess_id) values('t', 'f', 500);
insert into guess(question_id, person_id) values(21, 16);
insert into base_guess (guess, whitewalker, guess_id) values('t', 'f', 501);
insert into guess(question_id, person_id) values(22, 16);
insert into base_guess (guess, whitewalker, guess_id) values('t', 'f', 502);
insert into guess(question_id, person_id) values(23, 16);
insert into base_guess (guess, whitewalker, guess_id) values('f', 'f', 503);
insert into guess(question_id, person_id) values(24, 16);
insert into base_guess (guess, whitewalker, guess_id) values('f', 'f', 504);
insert into guess(question_id, person_id) values(25, 16);
insert into base_guess (guess, whitewalker, guess_id) values('t', 'f', 505);
insert into guess(question_id, person_id) values(26, 16);
insert into base_guess (guess, whitewalker, guess_id) values('f', 'f', 506);
insert into guess(question_id, person_id) values(27, 16);
insert into base_guess (guess, whitewalker, guess_id) values('f', 'f', 507);
insert into guess(question_id, person_id) values(28, 16);
insert into bonus_guess (guess, guess_id) values('Yes', 508);
insert into guess(question_id, person_id) values(29, 16);
insert into bonus_guess (guess, guess_id) values('No', 509);
insert into guess(question_id, person_id) values(30, 16);
insert into bonus_guess (guess, guess_id) values('Jon Snow', 510);
insert into guess(question_id, person_id) values(31, 16);
insert into bonus_guess (guess, guess_id) values('Longclaw', 511);
insert into guess(question_id, person_id) values(32, 16);
insert into bonus_guess (guess, guess_id) values('Daenerys Targaryen', 512);


