update question set answer = '2' where id = 1;
update question set answer = '2' where id = 2;
update question set answer = '2' where id = 3;
update question set answer = '2' where id = 4;
update question set answer = '0' where id = 5;
update question set answer = '0' where id = 6;
update question set answer = '2' where id = 7;
update question set answer = '0' where id = 8;
update question set answer = '0' where id = 9;
update question set answer = '2' where id = 10;
update question set answer = '0' where id = 11;
update question set answer = '0' where id = 12;
update question set answer = '0' where id = 13;
update question set answer = '0' where id = 14;
update question set answer = '2' where id = 15;
update question set answer = '2' where id = 16;
update question set answer = '2' where id = 17;
update question set answer = '0' where id = 18;
update question set answer = '2' where id = 19;
update question set answer = '2' where id = 20;
update question set answer = '2' where id = 21;
update question set answer = '2' where id = 22;
update question set answer = '2' where id = 23;
update question set answer = '2' where id = 24;
update question set answer = '2' where id = 25;
update question set answer = '0' where id = 26;
update question set answer = '0' where id = 27;
update question set answer = 'No' where id = 28;
update question set answer = 'No' where id = 29;
update question set answer = 'Arya Stark' where id = 30;
update question set answer = 'Catspaw Dagger' where id = 31;
update question set answer = 'No one' where id = 32;
